Corrected file for assembling and linking

diff --git a/Assembly_language/Sample_Programs/assemble_link b/Assembly_language/Sample_Programs/assemble_link
--- a/Assembly_language/Sample_Programs/assemble_link
+++ b/Assembly_language/Sample_Programs/assemble_link
@@ -1,18 +1,37 @@
 #!/bin/bash
 
-echo "Enter file name: "
-read asm_file
+read -p "Enter file name: " asm_file
 
-rm ${asm_file%.asm}.o
-echo "Deleted ${asm_file%.asm}.o" 
+if [ -e "$asm_file.asm" ]; then
+  echo "File '$asm_file.asm' found in directory... \n"
+  if [ -e "$asm_file.o" ]; then
+    echo "Found executable file, attempting deleting...\n"
+    echo "Attempting command rm '$asm_file.o'...\n"
+    rm "$asm_file.o"
+    echo "Delete complete, attempting NASM compilation...\n"
+    nasm -f elf "$asm_file.asm"
+    echo "Assembling complete, linking file...\n"
+    ld -m elf_i386 -s -o "$asm_file" "$asm_file.o"
+  else
+    nasm -f elf "$asm_file.asm"
+    echo "Assembling complete, linking file...\n"
+    ld -m elf_i386 -s -o "$asm_file" "$asm_file.o"
+  fi
+else
+  echo "File not found"
+  exit 1
+fi
 
-rm ${asm_file%.asm}
-echo "Deleted ${asm_file%.asm} executable file\n"
-echo "Attempting nasm compilation ...\n"
 
-nasm -f elf $asm_file -o ${asm_file%.asm}.o
-echo "Assembling complete, linking file...\n"
-  ${asm_file%.asm}.o -s -o ${asm_file%.asm}
-echo "Link complete, ready to execute...\n"
+# rm ${asm_file%.asm}.o
+# echo "Deleted ${asm_file%.asm}.o" 
+
+# rm ${asm_file%.asm}
+# echo "Deleted ${asm_file%.asm} executable file\n"
+# echo "Attempting nasm compilation ...\n"
 
 
+# nasm -f elf $asm_file -o ${asm_file%.asm}.o
+# echo "Assembling complete, linking file...\n"
+#   ${asm_file%.asm}.o -s -o ${asm_file%.asm}
+# echo "Link complete, ready to execute...\n"
